// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum RarityType {
  COMMON,
  UNCOMMON,
  RARE,
  MYTHIC
}

enum PackType {
  FIXED,
  RANDOM
}

enum TeamType {
  FIRE,
  FOREST,
  WATER,
  NEUTRAL
}
