// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { AdminSingleton, AdminSingletonTableId } from "./tables/AdminSingleton.sol";
import { CounterSingleton, CounterSingletonTableId } from "./tables/CounterSingleton.sol";
import { CardRaritySingleton, CardRaritySingletonData, CardRaritySingletonTableId } from "./tables/CardRaritySingleton.sol";
import { Packs, PacksData, PacksTableId } from "./tables/Packs.sol";
import { Users, UsersData, UsersTableId } from "./tables/Users.sol";
import { Cards, CardsData, CardsTableId } from "./tables/Cards.sol";
import { Ability, AbilityData, AbilityTableId } from "./tables/Ability.sol";
import { CardOnBoards, CardOnBoardsData, CardOnBoardsTableId } from "./tables/CardOnBoards.sol";
import { Decks, DecksData, DecksTableId } from "./tables/Decks.sol";
import { Matches, MatchesData, MatchesTableId } from "./tables/Matches.sol";
import { MatchesExtended, MatchesExtendedData, MatchesExtendedTableId } from "./tables/MatchesExtended.sol";
import { Players, PlayersData, PlayersTableId } from "./tables/Players.sol";
import { PlayerCardsDeck, PlayerCardsDeckTableId } from "./tables/PlayerCardsDeck.sol";
import { PlayerCardsHand, PlayerCardsHandTableId } from "./tables/PlayerCardsHand.sol";
import { PlayerCardsBoard, PlayerCardsBoardTableId } from "./tables/PlayerCardsBoard.sol";
import { PlayerCardsEquip, PlayerCardsEquipTableId } from "./tables/PlayerCardsEquip.sol";
import { PlayerCardsDiscard, PlayerCardsDiscardTableId } from "./tables/PlayerCardsDiscard.sol";
import { PlayerCardsSecret, PlayerCardsSecretTableId } from "./tables/PlayerCardsSecret.sol";
import { PlayerCardsTemp, PlayerCardsTempTableId } from "./tables/PlayerCardsTemp.sol";
import { ActionHistory, ActionHistoryData, ActionHistoryTableId } from "./tables/ActionHistory.sol";
import { Tasks, TasksData, TasksTableId } from "./tables/Tasks.sol";
