// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { AbilityTrigger } from "./../common.sol";

/**
 * @title IAbilitySecretsSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAbilitySecretsSystem {
  function ResolveSecret(
    bytes32 game_uid,
    AbilityTrigger secret_trigger,
    bytes32 secret_card,
    bytes32 trigger
  ) external;

  function TriggerSecrets(
    AbilityTrigger secret_trigger,
    bytes32 game_uid,
    bytes32 trigger_card
  ) external returns (bool);

  function TriggerPlayerSecrets(
    AbilityTrigger secret_trigger,
    bytes32 game_uid,
    bytes32 player
  ) external returns (bool);
}
