// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAbilitySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAbilitySystem {
  function UseAbility(bytes32 ability_key, bytes32 caster, bytes32 target, bool is_card) external;
}
