// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { CardsData } from "./../index.sol";

/**
 * @title IConfigSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IConfigSystem {
  function initCard() external;

  function getCard(string memory id) external view returns (CardsData memory _table);

  function setCard(string memory id, CardsData calldata data) external;
}
