// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IDebugSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IDebugSystem {
  function IsBoardCard(bytes32 key) external view returns (bool);

  function IsEquipment(bytes32 key) external view returns (bool);

  function SetGameEnd(bytes32 game_uid) external;
}
