// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IEndTurnSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IEndTurnSystem {
  function EndTurn(
    bytes32 game_key,
    bytes32 player_key
  ) external returns (bytes32 opponent_player_key, bytes32 board_card_key, int8 mana, int8 mana_max);

  function getOpponentPlayer(bytes32 game_key, bytes32 player_key) external view returns (bytes32 opponent_player_key);
}
