// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameStartSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameStartSystem {
  function GameSetting(string memory game_uid) external;

  function PlayerSetting(string memory username, string memory game_uid, string memory desk_id, bool is_ai) external;
}
