// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGameLogicSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameLogicSystem {
  function GameSetting(string memory game_uid) external returns (bytes32 key);

  function PlayerSetting(string memory username, string memory game_uid, bytes32 desk_key) external;

  function PlayCard(bytes32 card_key, uint8 slot) external;

  function AttackTarget(bytes32 card_key, uint8 slot) external;

  function AttackPlayer(bytes32 card_key, uint8 slot) external;

  function Move(bytes32 card_key, uint8 slot) external;

  function EndTurn(bytes32 card_key, uint8 slot) external;
}
