// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGmSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGmSystem {
  function AddCard(
    string memory game_uid,
    string memory player_name,
    string memory card_name
  ) external returns (bytes32);

  function AddCardOnEmptySlots(
    string memory game_uid,
    string memory player_name,
    string memory card_name
  ) external returns (bytes32);

  function setMana(bytes32 game_key) external;
}
