// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { MatchesData } from "./../index.sol";

/**
 * @title IMatchSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMatchSystem {
  function StartMatchmaking(uint8 nb_players) external returns (uint256, MatchesData memory);

  function CheckMatchmaking(uint256 matching_id) external view returns (MatchesData memory);
}
