// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IMatchSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMatchSystem {
  function StartMatchmaking(string memory game_uid, uint256 nplayer) external;
}
