// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Slot } from "./../../libs/SlotLib.sol";

/**
 * @title IMoveSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMoveSystem {
  function Move(bytes32 card_key, Slot memory slot) external;
}
