// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { RarityType } from "./../common.sol";

/**
 * @title IPacksSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPacksSystem {
  function OpenPack(bytes32 key) external;

  function getRandomCardByRarity(RarityType rarity) external view returns (bytes32);

  function getRandomRarity(uint8[] memory rarities) external view returns (RarityType);
}
