// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISelectSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISelectSystem {
  function SelectCard(bytes32 game_uid, bytes32 card_uid) external;

  function SelectPlayer() external;

  function SelectSlot() external;

  function SelectChoice() external;

  function CancelSelection() external;
}
