// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Slot } from "./../../libs/SlotLib.sol";

/**
 * @title ISlotSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISlotSystem {
  function GetAllSlot() external pure returns (Slot[] memory);

  function GetRandomEmptySlot(bytes32 player_key) external view returns (Slot memory);

  function GetSlotCard(bytes32 game_key, Slot memory slot) external view returns (bytes32);

  function GetEmptySlots(bytes32 player_key) external view returns (Slot[] memory);

  function ClearCardFromSlot(bytes32 player_key, bytes32 card_key) external;
}
