// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IAbilitySystem } from "./IAbilitySystem.sol";
import { IActionSystem } from "./IActionSystem.sol";
import { IAttackSystem } from "./IAttackSystem.sol";
import { IConditionSystem } from "./IConditionSystem.sol";
import { IConfigSystem } from "./IConfigSystem.sol";
import { ICounterSystem } from "./ICounterSystem.sol";
import { IDebugSystem } from "./IDebugSystem.sol";
import { IDeckSystem } from "./IDeckSystem.sol";
import { IEffect1System } from "./IEffect1System.sol";
import { IEffect2System } from "./IEffect2System.sol";
import { IEffect3System } from "./IEffect3System.sol";
import { IEffect4System } from "./IEffect4System.sol";
import { IEffect5System } from "./IEffect5System.sol";
import { IEffect6System } from "./IEffect6System.sol";
import { IEffectSystem } from "./IEffectSystem.sol";
import { IEndTurnSystem } from "./IEndTurnSystem.sol";
import { IFilterSystem } from "./IFilterSystem.sol";
import { IGameStartSystem } from "./IGameStartSystem.sol";
import { IGmSystem } from "./IGmSystem.sol";
import { IMarketSystem } from "./IMarketSystem.sol";
import { IMatchSystem } from "./IMatchSystem.sol";
import { IMoveSystem } from "./IMoveSystem.sol";
import { IPacksSystem } from "./IPacksSystem.sol";
import { IPlayCardSystem } from "./IPlayCardSystem.sol";
import { ISelectSystem } from "./ISelectSystem.sol";
import { ISlotSystem } from "./ISlotSystem.sol";
import { ITasksSystem } from "./ITasksSystem.sol";
import { IUsersSystem } from "./IUsersSystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IAbilitySystem,
  IActionSystem,
  IAttackSystem,
  IConditionSystem,
  IConfigSystem,
  ICounterSystem,
  IDebugSystem,
  IDeckSystem,
  IEffect1System,
  IEffect2System,
  IEffect3System,
  IEffect4System,
  IEffect5System,
  IEffect6System,
  IEffectSystem,
  IEndTurnSystem,
  IFilterSystem,
  IGameStartSystem,
  IGmSystem,
  IMarketSystem,
  IMatchSystem,
  IMoveSystem,
  IPacksSystem,
  IPlayCardSystem,
  ISelectSystem,
  ISlotSystem,
  ITasksSystem,
  IUsersSystem
{

}
