using System.Collections;
using System.Collections.Generic;
using Mud;
using UnityEngine;

namespace Mud
{
/* Autogenerated file. Do not edit manually. */
    enum SelectorType
    {
        None,
        SelectTarget,
        SelectorCard,
        SelectorChoice
    }

    enum RarityType
    {
        COMMON,
        UNCOMMON,
        RARE,
        MYTHIC
    }

    enum PackType
    {
        FIXED,
        RANDOM
    }

    enum TeamType
    {
        FIRE,
        FOREST,
        WATER,
        NEUTRAL
    }

    enum GameType
    {
        SOLO,
        ADVENTURE,
        MULTIPLAYER,
        HOST_P2P,
        OBSERVER
    }

    enum GameMode
    {
        CASUAL,
        RANKED
    }

    enum GameState
    {
        INIT,
        PLAY,
        GAME_ENDED
    }

    enum GamePhase
    {
        NONE,
        START_TURN,
        MAIN,
        END_TURN
    }

    enum CardType
    {
        NONE,
        HERO,
        CHARACTER,
        SPELL,
        ARTIFACT,
        SECRET,
        EQUIPMENT
    }

    enum AbilityTrigger
    {
        NONE,
        ONGOING,
        ACTIVATE,
        ON_PLAY,
        ON_PLAY_OTHER,
        START_OF_TURN,
        END_OF_TURN,
        ON_BEFORE_ATTACK,
        ON_AFTER_ATTACK,
        ON_BEFORE_DEFEND,
        ON_AFTER_DEFEND,
        ON_KILL,
        ON_DEATH,
        ON_DEATH_OTHER
    }

    enum AbilityTarget
    {
        None,
        Self,
        PlayerSelf,
        PlayerOpponent,
        AllPlayers,
        AllCardsBoard,
        AllCardsHand,
        AllCardsAllPiles,
        AllSlots,
        AllCardData,
        PlayTarget,
        AbilityTriggerer,
        EquippedCard,
        SelectTarget,
        CardSelector,
        ChoiceSelector,
        LastPlayed,
        LastTargeted,
        LastDestroyed,
        LastSummoned
    }

    enum Team
    {
        FIRE,
        FOREST,
        WATER,
        NEUTRAL
    }

    enum Action
    {
        PlayCard,
        Attack,
        AttackPlayer,
        Move,
        CastAbility,
        SelectCard,
        SelectPlayer,
        SelectSlot,
        SelectChoice,
        CancelSelect,
        EndTurn,
        ChangeMana,
        AddStatus,
        ChangeCard
    }

    enum PileType
    {
        None,
        Board,
        Hand,
        Deck,
        Discard,
        Secret,
        Equipped,
        Temp
    }

    enum EffectStatType
    {
        None,
        Attack,
        HP,
        Mana
    }

    enum ConditionObjType
    {
        ConditionCardType
    }

    enum TraitData
    {
        Dragon,
        Growth,
        SpellDamage,
        Wolf
    }

    enum EffectAttackerType
    {
        Self,
        AbilityTriggerer,
        LastPlayed,
        LastTargeted
    }

    enum Status
    {
        None,
        Armor,
        Attack,
        Deathtouch,
        Flying,
        Fury,
        Hp,
        Intimidate,
        Invicibility,
        Lifesteal,
        Paralysed,
        Poisoned,
        Protected,
        Shell,
        Silenced,
        Sleep,
        SpellImmunity,
        Stealth,
        Taunt,
        Trample
    }
}

static class MudEnum
{
    
    public static uint CombineUint32(uint a, uint b, uint c, uint d)
    {
        uint result = ((uint)a << 24) | ((uint)b << 16) | ((uint)c << 8) | (uint)d;
        return result;
    }

    public static (uint, uint, uint, uint) SplitUint32(uint value)
    {
        uint a = (uint)((value >> 24) & 0xFF);
        uint b = (uint)((value >> 16) & 0xFF);
        uint c = (uint)((value >> 8) & 0xFF);
        uint d = (uint)(value & 0xFF);
        return (a, b, c, d);
    }
    
    public static TcgEngine.GameState ConvertGameState(Mud.GameState state)
    {
        switch (state)
        {
            case GameState.INIT:
                return TcgEngine.GameState.Connecting;
            case GameState.PLAY:
                return TcgEngine.GameState.Play;
            case GameState.GAME_ENDED:
                return TcgEngine.GameState.GameEnded;
        }

        return TcgEngine.GameState.Connecting;
    }
    
    public static TcgEngine.GamePhase ConvertGamePhase(Mud.GamePhase phase)
    {
        switch (phase)
        {
            case GamePhase.NONE:
                return TcgEngine.GamePhase.None;
            case GamePhase.START_TURN:
                return TcgEngine.GamePhase.StartTurn;
            case GamePhase.MAIN:
                return TcgEngine.GamePhase.Main;
            case GamePhase.END_TURN:
                return TcgEngine.GamePhase.EndTurn;
        }

        return TcgEngine.GamePhase.None;
    }
    
    public static TcgEngine.SelectorType ConvertSelectorType(Mud.SelectorType type)
    {
        switch (type)
        {
            case SelectorType.None:
                return TcgEngine.SelectorType.None;
            case SelectorType.SelectTarget:
                return TcgEngine.SelectorType.SelectTarget;
            case SelectorType.SelectorCard:
                return TcgEngine.SelectorType.SelectorCard;
            case SelectorType.SelectorChoice:
                return TcgEngine.SelectorType.SelectorChoice;
        }

        return TcgEngine.SelectorType.None;
    }
    
    public static TcgEngine.StatusType CoverStatus(Mud.Status status)
    {
        switch (status)
        {
            case Status.None:
                return TcgEngine.StatusType.None;
            case Status.Armor:
                return TcgEngine.StatusType.Armor;
            case Status.Paralysed:
                return TcgEngine.StatusType.Paralysed;
            case Status.Deathtouch:
                return TcgEngine.StatusType.Deathtouch;
            case Status.Flying:
                return TcgEngine.StatusType.Flying;
            case Status.Fury:
                return TcgEngine.StatusType.Fury;
            case Status.Shell:
                return TcgEngine.StatusType.Shell;
            case Status.Sleep:
                return TcgEngine.StatusType.Sleep;
            case Status.Stealth:
                return TcgEngine.StatusType.Stealth;
            case Status.Attack:
                return TcgEngine.StatusType.AttackBonus;
            case Status.Hp:
                return TcgEngine.StatusType.HPBonus;
            case Status.Intimidate:
                return TcgEngine.StatusType.Intimidate;
            case Status.Invicibility:
                return TcgEngine.StatusType.Invincibility;
            case Status.Lifesteal:
                return TcgEngine.StatusType.LifeSteal;
            case Status.Poisoned:
                return TcgEngine.StatusType.Poisoned;
            case Status.Protected:
                return TcgEngine.StatusType.Protected;
            case Status.Silenced:
                return TcgEngine.StatusType.Silenced;
            case Status.SpellImmunity:
                return TcgEngine.StatusType.SpellImmunity;
            case Status.Taunt:
                return TcgEngine.StatusType.Protection;
            case Status.Trample:
                return TcgEngine.StatusType.Trample;
        
            
            //todo

        }

        return TcgEngine.StatusType.None;
    }
}